version: '3.1'

services:
  mailbagit:
    image: ualbanyarchives/mailbagit:dev
    volumes:
      - '../sampleData:/data'
      - '.:/mailbagit'
    tty: true
    stdin_open: true
    working_dir: /mailbagit
    command: bash -c "pip install --upgrade pip && pip install -e . && cd /data && bash"